package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseErrorcode<M extends BaseErrorcode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCode(java.lang.Integer code) {
		set("code", code);
	}
	
	public java.lang.Integer getCode() {
		return getInt("code");
	}

	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}
	
	public java.lang.String getMsg() {
		return getStr("msg");
	}

}
