package com.demo.common.model;

import com.demo.common.model.base.BaseErrorcode;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Errorcode extends BaseErrorcode<Errorcode> {
	public Record geterrmsg(int code){
			String sql = "SELECT * FROM errorcode WHERE code = ?";
			
			return Db.findFirst(sql,code);
			
			
		}
}
