package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseTags;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public List<Record> listTags(){
		String sql = "SELECT * FROM tags";
		return Db.find(sql);
		
	}
}
