package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
	
	
      public List<Record> getlist(int id){
    	 String sql = "SELECT * FROM user WHERE id = ?";
    	  
		return Db.find(sql,id);
    	  
      }
      
      
      public boolean updataspw(int id,String psw){
    	  String sql = "UPDATE user SET psw = ? WHERE id = ?";
    	 
    	  
		return  Db.update(sql, psw,id)>0;
      }
      
      public Record getUser(int id){
    		
    	  String sql = "SELECT * FROM user WHERE id = ?";
    	return  Db.findFirst(sql, id);
  	
  		
  	}
      
      
      
	public Record get(String account){
  		
    	  String sql = "SELECT * FROM user WHERE account = ?";
    	return  Db.findFirst(sql, account);
  	
  		
  	}
      
      /**
       * 
       * @param id
       * 修改用户信息
       * @return
       */
      public boolean changuserinfo(int id,String account,String psw){
    	  String sql = "UPDATE user SET account=? , psw=? WHERE id=?;";
    		return  Db.update(sql,account,psw,id)>0;
	
    	
		
  		
  	}
      
      
      
     
      
}
